### PR TITLE
API improvement and implementation of error handling

### LINKED ISSUE #232: BUG: Core Chain_Delete_Image() effect when deleting non existing image
Descritpion of the problem
=====================
When `Chain_Delete_Image()` is called for a non existing images it deletes one unidentified image of the chain. It is not easy to see which image is deleted:
- the last one when the index is greater than the largest existing index?
- the 0th one when the index is lower than 0
- the active image 

Steps to reproduce
------------------------
1. Setup a chain with at least two images. They will have indices 0 and 1. 
2. `Chain_Get_NOI()` is 2
3. Try delete an image with index >= 2 or index < 0
4. `Chain_Get_NOI()` is 1. 

Expected behaviour
-------------------------
When `Chain_Delete_Image()` is given an index which does not corresponds to any image:
1. It must not affect the pre-existing images (NOI must be unchanged) 
2. It should raise a meaningful `[Warning]` in the log

### PR DESCRIPTION
**Pull request by smavros**
- Chain_delete_image() bug fix #232
- Modified python test for deletion of non existing image

### CODE REVIEW

**Comment by GPMueller** [comment]
Actually it may be better to re-implement the current exceptions as classes derived from `std::exception` see e.g. https://stackoverflow.com/questions/6755991/catching-stdexception-by-reference.

File: core/include/utility/Exception.hpp [hunk 1]
```diff
@@ -16,9 +16,14 @@ namespace Utility
...
         Non_existing_Chain         = Exception_Non_existing_Chain
+        // TODO: from Chain.cpp
+        // Last image deletion ?
+        // Empty clipboard     ?
 	};
   
-  void Handle_exception( const Exception & ex, int idx_image, int idx_chain );
+  void Spirit_Exception( const Exception & ex, int idx_image=-1, int idx_chain=-1 );
+
+  void Handle_Exception( int idx_image, int idx_chain );
```
Comment (smavros) [inline core/include/utility/Exception.hpp]: Most common case is not to have the `idx_image` in the call of the function in which there is a `catch`. Probably it would be better to re-arrange the function's arguments so we could use the c++ default arguments mechanism.
```c++
void Handle_Exception( int idx_chain=-1, int idx_image=-1 );
```
thus, we could avoid the initialization of a variable outside `int idx_image=-1` outside of the `try{ ... } catch{ ... }`

File: core/src/Spirit/Chain.cpp [hunk 2]
```diff
@@ -9,710 +9,726 @@
...
 
-bool Chain_Jump_To_Image(State * state, int idx_image_i, int idx_chain_i)
+bool Chain_prev_Image( State * state, int idx_chain )
 {
-    int idx_image = idx_image_i, idx_chain = idx_chain_i;
-    std::shared_ptr<Data::Spin_System> image;
-    std::shared_ptr<Data::Spin_System_Chain> chain;
-    
-    // Fetch correct indices and pointers
+    int idx_image = -1;
```
Comment (smavros) [inline core/src/Spirit/Chain.cpp]: It is probably not a problem to have the definition of `idx_image` outside of the `try{ ... } catch{ ... }` (so to have it available in both scopes) but a better way would be to change argument's order in `Utility::Handle_Exception()` function [(see that comment)](https://github.com/spirit-code/spirit/pull/281/commits/c173dd19f953859a952baf8c82e0c0ca089bb520#r132786843)

File: core/src/Spirit/Chain.cpp [hunk 3]
```diff
@@ -9,710 +9,726 @@
...
+    catch( ... )
     {
-        Utility::Handle_exception( ex, idx_image, idx_chain );
-        return E_arr_interpolated;
+        Utility::Handle_Exception( idx_image, idx_chain );
+        
+        // XXX: what should we return in that situation
+        std::vector<std::vector<float>> E_at_failure ( 1 );
+            E_at_failure[0] = std::vector<float> ( 1, 0 );
+        return E_at_failure;
```
Comment (smavros) [inline core/src/Spirit/Chain.cpp]: I am not sure if this is the right thing to return in case of `Exception` throw. It is the simplest think that I can think of. Any use of eg `chain->E_array_interpolated.size()` for returning a vector with proper length, would possibly the reason of the exception throw.

File: core/include/utility/Exception.hpp [hunk 4]
```diff
@@ -16,9 +16,14 @@ namespace Utility
 		Unknown_Exception          = Exception_Unknown_Exception,
         Non_existing_Image         = Exception_Non_existing_Image,
         Non_existing_Chain         = Exception_Non_existing_Chain
+        // TODO: from Chain.cpp
+        // Last image deletion ?
+        // Empty clipboard     ?
```
Comment (smavros) [inline core/include/utility/Exception.hpp]: In the file Chain.cpp there are some functions which are logging `Warning` messages in case of illegal actions like 

- Deletion of the last image of the chain
- Copy image from an empty clipboard

Should we turn those cases to `Exceptions` and eliminate the logging from the body of those functions?

File: core/include/utility/Exception.hpp (hunk 1 above)
Comment (GPMueller) [inline core/include/utility/Exception.hpp]: I don't think this is necessary, you can just pass in `-1`. I would prefer consistency among all these functions.

File: core/src/Spirit/Chain.cpp (hunk 3 above)
Comment (GPMueller) [inline core/src/Spirit/Chain.cpp]: What you say is correct, so it makes sense what you wrote. It may result in an error in user code, if this is not expected, but that is not an issue for the API.

File: core/include/utility/Exception.hpp (hunk 4 above)
Comment (GPMueller) [inline core/include/utility/Exception.hpp]: As long as the resulting log messages will be equivalently clear that would be the right thing to do. In the cases you mention that may not be possible, I'm not quite sure right now.

File: core/src/Spirit/Configurations.cpp [hunk 5]
```diff
@@ -13,7 +13,9 @@
 #endif
 
 
-std::function< bool(const Vector3&, const Vector3&) > get_filter(Vector3 position, const float r_cut_rectangular[3], float r_cut_cylindrical, float r_cut_spherical, bool inverted)
+std::function<bool(const Vector3&, const Vector3&)> 
+get_filter( Vector3 position, const float r_cut_rectangular[3], float r_cut_cylindrical,
```
Comment (smavros) [inline core/src/Spirit/Configurations.cpp]: The function `get_filter()` and `filter_to_string()` are not directly exposed to the user through the API. Instead they are called by API functions. We do not have to guard for `Exceptions` since those will be thrown to the API functions which are wrapped around `try( ... ) catch( ... )`.

File: core/src/Spirit/Collection.cpp [hunk 6]
```diff
@@ -1,9 +1,18 @@
...
+#include <utility/Exception.hpp>
 #include <data/State.hpp>
 
 int Collection_Get_NOC(State * state)
 {
-    return state->noc;
+    try
+    {
+        return state->noc;
+    }
```
Comment (smavros) [inline core/src/Spirit/Collection.cpp]: Probably we do not need that `try( ... )catch( ... )` here.

Comment (GPMueller) [inline core/src/Spirit/Collection.cpp]: If an invalid `State *` is passed here, `state->noc` may throw. The try/catch should therefore stay.

File: core/src/Spirit/System.cpp [hunk 7]
```diff
@@ -6,171 +6,175 @@
...
 {
-    return state->idx_active_image;
+    try
+    {
+        return state->idx_active_image;
+    }
+    catch( ... )
+    {
+        Utility::Handle_Exception();
+        return -1;
```
Comment (smavros) [inline core/src/Spirit/System.cpp]: In case of `Exception` which is handled without termination of Spirit, I think it is better to return `-1` since `0` is a legal system index.

File: core/src/Spirit/Simulation.cpp [hunk 8]
```diff
@@ -11,389 +11,441 @@
...
-		if (state->simulation_information_collection)
-			return (float)state->simulation_information_collection->method->getIterationsPerSecond();
-    }
-
-	return 0;
 }
 
 
 const char * Simulation_Get_Optimizer_Name(State *state, int idx_image, int idx_chain)
 {
```
Comment (smavros) [inline core/src/Spirit/Simulation.cpp]: This function is broken. It always returns an empty string. Should I add an issue?
